EPSILON = 2e-6

SID = 'sid'
KEY = 'key'
VALUE = 'value'
# READOUT = 'readout'
EDGE = 'edge'
ROOT = 'root'
TOKEN = 'token'
NUMBER = 'number'

KEY2KEY = (KEY, EDGE, KEY)
KEY2VALUE = (KEY, EDGE, VALUE)
# KEY2READOUT = (KEY, EDGE, READOUT)
VALUE2VALUE = (VALUE, EDGE, VALUE)
# VALUE2READOUT = (VALUE, EDGE, READOUT)
