EPSILON = 2e-6

SID = 'sid'
KEY = 'key'
VALUE = 'value'
TARGET = 'target'
EDGE = 'edge'
READOUT = 'readout'

KEY2KEY = (KEY, EDGE, KEY)
KEY2VALUE = (KEY, EDGE, VALUE)
KEY2TARGET = (KEY, EDGE, TARGET)
VALUE2VALUE = (VALUE, EDGE, VALUE)
VALUE2TARGET = (VALUE, EDGE, TARGET)
